name: Build DeltaTruss

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pyinstaller openpyxl pywin32

      - name: Build exe
        run: |
          python -m PyInstaller --onefile --windowed --name DeltaTruss `
            --hidden-import openpyxl `
            --hidden-import win32api `
            --hidden-import CICD.auto_poll `
            --hidden-import CICD.auto_download `
            --hidden-import CICD.auto_rename `
            --hidden-import CICD.auto_trigger `
            --hidden-import CICD.auto_cases `
            --hidden-import CICD.auto_runner `
            --icon DeltaTruss.ico `
            main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: DeltaTruss
          path: dist\DeltaTruss.exe
