name: Build DeltaTruss

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pyinstaller openpyxl

      - name: Build exe
        run: |
          python -m PyInstaller --onefile --windowed --name DeltaTruss --hidden-import openpyxl main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: DeltaTruss
          path: dist\DeltaTruss.exe
